### PR TITLE
Fixing accents like 'êé' and others

### PR DESCRIPTION
**Pull request by rafaelqm**
Hi, first thank by letting this code public, as you say, there is nothing around the web like this.

So I Have problems with accents, so this fix it. 

Thanks again.

### CODE REVIEW

**Comment by rafaelqm** [comment]
Hi, 
If you use chr() it return the error:
`iconv(): Detected an incomplete multibyte character in input string`
At line 927:
`$utf8 = iconv($srcEnc, 'UTF-8', chr($code));`
So with mb_chr(), it works perfectly.

This is the RTF:
`{\rtf1\ansi\deff0
{\fonttbl{\f0\fnil Courier New;}}
{\colortbl ;\red255\green255\blue255;}
{\stylesheet{\s4\sbasedon2\snext4 default;}{\s7\sbasedon2\snext7 default;}{\s5\sbasedon2\snext5 default;}{\s2 default;}{\s8\sbasedon2\snext8 default;}{\s1\sbasedon2\snext1 default;}{\s6\sbasedon2\snext6 default;}{\s3\sbasedon2\snext3 default;}}

\s1\ql\f0\fs24\i0\b\ul0\highlight1\cf0 CREATININA\par
\ql\i\b0\par
\ql\fs20                                                                    \par
\pard\s3\ql\i0 RESULTADO....\b :\i  \i0              0,7\b0     \b mg/dl       \b0   \par
\ql\fs22        \par
\ql\fs16\i                        \i0  Valores de Refer\'eancia: 0.6 A 1.3 mg/dL\i\par
\ql                                                                        \par
\ql\fs20\i0\par
\pard\s4\ql\fs16 Material:   Sangue                                                                               \par
\pard\s5\ql Metodo..:   Cin\'e9tica Enzim\'e1tica                                  \par
\ql\par
\pard\s6\ql\par
\pard\s7\ql\par
\ql\par
\pard\s8\ql Data coleta: 17/12/2018\par
\ql\fs22\i0\b0\ul0\highlight0\par
}`

**Comment by mhtamala** [comment]
I can't seem to reproduce the error with the given rtf source code.
Please use the last updated version of the rtf-html-php package including my **last Pull request**.

I still disagree with this Pull for 2 reasons:

1. I can't reproduce the error

2. `mb_chr()` is defined only in PHP >= 7.2.0 making the project restricted only to these higher versions

regards

**Comment by henck** [comment]
I agree with @mhtamala's point about PHP versions. I'd like to keep this project compatible with the lowest possible version of PHP, so that would rule out the use of `mb_chr()`.

**Comment by rafaelqm** [comment]
No problems. With PHP 7.1 this erro occurs, and the solution was using mb_chr().

**Pull request closed without merging**
